<?php
// Constants
define('TRAWLER_PATH_ROOT', realpath(__DIR__ . DIRECTORY_SEPARATOR . '..'));
define('TRAWLER_PATH_APPLICATION', TRAWLER_PATH_ROOT . DIRECTORY_SEPARATOR . 'application');
define('TRAWLER_PATH_INCLUDE', TRAWLER_PATH_ROOT . DIRECTORY_SEPARATOR . 'include');
define('TRAWLER_PATH_LIBRARIES', TRAWLER_PATH_ROOT . DIRECTORY_SEPARATOR . 'application' . DIRECTORY_SEPARATOR . 'libraries');
define('TRAWLER_PATH_SMARTY', TRAWLER_PATH_LIBRARIES . DIRECTORY_SEPARATOR . 'Smarty');
define('TRAWLER_PATH_MODULES', TRAWLER_PATH_ROOT . DIRECTORY_SEPARATOR . 'application' . DIRECTORY_SEPARATOR . 'modules');
define('TRAWLER_PATH_SETTINGS', TRAWLER_PATH_ROOT . DIRECTORY_SEPARATOR . 'application' . DIRECTORY_SEPARATOR . 'settings');
define('TRAWLER_PATH_INDEX', TRAWLER_PATH_ROOT . DIRECTORY_SEPARATOR . basename($_SERVER['SCRIPT_NAME']));
define('TRAWLER_PATH_STATIC', TRAWLER_PATH_ROOT . DIRECTORY_SEPARATOR . 'static');

if ( !defined( 'TRAWLER_PATH_FILES' ) )
{
    define( 'TRAWLER_PATH_FILES', TRAWLER_PATH_ROOT . DIRECTORY_SEPARATOR . 'file' );
}

if ( !defined( 'TRAWLER_URL_ROOT' ) )
{
    define( 'TRAWLER_URL_ROOT', $_SERVER['HTTP_HOST'] . dirname($_SERVER['SCRIPT_NAME']) . DIRECTORY_SEPARATOR );
}

if ( !defined( 'TRAWLER_ERROR_REPORTING' ) )
{
    //define('TRAWLER_ERROR_REPORTING', 1);
    define('TRAWLER_ERROR_REPORTING', 0);
}

if ( !defined( 'TRAWLER_DISPLAY_ERRORS' ) )
{

    //define('TRAWLER_DISPLAY_ERRORS', 'on');
    define('TRAWLER_DISPLAY_ERRORS', 'off');
}

if ( !defined( 'TRAWLER_LOG_ERRORS' ) )
{
    define('TRAWLER_LOG_ERRORS', 1);
}

/*
 if( !defined('TRAWLER_IP_PROXY_HEADER')){
	define('TRAWLER_IP_PROXY_HEADER', 'HTTP_X_FORWARDED_FOR');
}
 */
